### ISSUE TITLE
Request to use python-whois instead of whois.

### ISSUE THREAD

**Issue by noptrix** [t4d/PhishingKitHunter#1]
Hi there!

Is it possible that you go with 'https://pypi.org/project/python-whois/' for phishingkithunter? The 'whois' lib is very old and not developed anymore. Cheers

**Comment by t4d** [comment]
ok I will check for that soon. Anyway feel free to make a pull request if you made changes by yourself.

**Comment by t4d** [comment]
This v0.8.1 version use the python-whois lib (https://github.com/t4d/PhishingKitHunter/commit/63a90b15e9d02a9206b883e8cf9fedd4b534130e), and is more PEP8 compliant. Feel free to test and let us know.

**Comment by noptrix** [comment]
@t4d awesome. yes, i will test it now and i can re-package phishingkithunter to blackarch. cheers

**Comment by noptrix** [comment]
@t4d just tested it. everything works. thanks
